
SELECT NAME FROM v$database;

Select Name from v$tablespace;

DROP USER "CLARITYREPORTUSERX" CASCADE;
DROP USER "CLARITYLOOKUPUSERX" CASCADE;
DROP USER "CLARITYUSERX" CASCADE;
DROP TABLESPACE "CLARITYTESTSPACE" INCLUDING CONTENTS AND DATAFILES;

-- CLARITY501 A

CREATE SMALLFILE TABLESPACE "CLARITYTESTSPACE"
DATAFILE SIZE 500M AUTOEXTEND ON NEXT 50M
MAXSIZE UNLIMITED
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

-- Create standard Clarity Usert

CREATE USER "CLARITYUSERX"  IDENTIFIED BY "CLARITYUSERX" DEFAULT TABLESPACE "CLARITYTESTSPACE" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "CLARITYUSERX";
GRANT "CONNECT" TO "CLARITYUSERX";
GRANT "RESOURCE" TO "CLARITYUSERX";
GRANT CREATE VIEW TO "CLARITYUSERX";
GRANT CREATE MATERIALIZED VIEW TO "CLARITYUSERX";
GRANT CREATE PROCEDURE TO "CLARITYUSERX";
GRANT CREATE PUBLIC SYNONYM TO "CLARITYUSERX";
GRANT CREATE SEQUENCE TO "CLARITYUSERX";
GRANT CREATE SYNONYM TO "CLARITYUSERX";
GRANT CREATE TABLE TO "CLARITYUSERX";
GRANT CREATE TRIGGER TO "CLARITYUSERX";
GRANT CREATE TYPE TO "CLARITYUSERX";
GRANT CREATE ANY CONTEXT TO "CLARITYUSERX";

-- Create Reporting (ETL) User

CREATE USER "CLARITYREPORTUSERX"  IDENTIFIED BY "CLARITYUSERX" DEFAULT TABLESPACE "CLARITYTESTSPACE" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "CLARITYREPORTUSERX";
GRANT "CONNECT" TO "CLARITYREPORTUSERX";
GRANT "RESOURCE" TO "CLARITYREPORTUSERX";
GRANT CREATE VIEW TO "CLARITYREPORTUSERX";
GRANT CREATE MATERIALIZED VIEW TO "CLARITYREPORTUSERX";
GRANT CREATE PROCEDURE TO "CLARITYREPORTUSERX";
GRANT CREATE PUBLIC SYNONYM TO "CLARITYREPORTUSERX";
GRANT CREATE SEQUENCE TO "CLARITYREPORTUSERX";
GRANT CREATE TABLE TO "CLARITYREPORTUSERX";
GRANT CREATE TRIGGER TO "CLARITYREPORTUSERX";


-- Create Lookup User

CREATE USER "CLARITYLOOKUPUSERX"  IDENTIFIED BY "CLARITYUSERX" DEFAULT TABLESPACE "CLARITYTESTSPACE" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "CLARITYLOOKUPUSERX";
GRANT "CONNECT" TO "CLARITYLOOKUPUSERX";
GRANT "RESOURCE" TO "CLARITYLOOKUPUSERX";
GRANT CREATE VIEW TO "CLARITYLOOKUPUSERX";
GRANT CREATE MATERIALIZED VIEW TO "CLARITYLOOKUPUSERX";
GRANT CREATE PROCEDURE TO "CLARITYLOOKUPUSERX";
GRANT CREATE PUBLIC SYNONYM TO "CLARITYLOOKUPUSERX";
GRANT CREATE SEQUENCE TO "CLARITYLOOKUPUSERX";
GRANT CREATE SYNONYM TO "CLARITYLOOKUPUSERX";
GRANT CREATE TABLE TO "CLARITYLOOKUPUSERX";
GRANT CREATE TRIGGER TO "CLARITYLOOKUPUSERX";
GRANT CREATE TYPE TO "CLARITYLOOKUPUSERX";


PURGE RECYCLEBIN;
COMMIT;

ALTER SESSION SET CURRENT_SCHEMA = "CLARITYUSERX";

@/tmp/OracleSetup/json_v1_0_5/install.sql;
COMMIT;

EXIT
